//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Child
    {
        public int Serial { get; set; }
        public System.DateTime Date { get; set; }
        public string Type { get; set; }
        public decimal Amt { get; set; }
        public string AccNo { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
    }
}
